// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwec4_SMdFCHZfhiFW55FQ7NZxWb-Ur4',
    appId: '1:212755462711:android:34b24f8e1ccab895a6ddb2',
    messagingSenderId: '212755462711',
    projectId: 'flutteremergency-bb7ca',
    authDomain: 'flutteremergency.firebaseapp.com',
    storageBucket: 'flutteremergency-bb7ca.firebasestorage.app',
    measurementId: 'G-DQW99JW51L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFwec4_SMdFCHZfhiFW55FQ7NZxWb-Ur4',
    appId: '1:212755462711:android:34b24f8e1ccab895a6ddb2',
    messagingSenderId: '212755462711',
    projectId: 'flutteremergency-bb7ca',
    storageBucket: 'flutteremergency-bb7ca.firebasestorage.app',
  );
}
